# This is a basic workflow to help you get started with Actions

name: AutoBuild

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  auto_build:
    uses: VanyaHuaman/GithubActionsTester/.github/workflows/build.yml@master
    secrets: inherit
    with:
      variant: ${{ github.event.client_payload.variant }}
      version: ${{ github.event.client_payload.version }}
