# This is a basic workflow to help you get started with Actions

name: AutoBuild

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  auto_build:
    runs-on: ubuntu-latest
    uses: VanyaHuaman/GithubActionsTester/.github/workflows/build.yml@master
    secrets: inherit

