name: Build

on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Prod for both Production and Staging.'
        type: string
        required: false
      version:
        description: 'version passed'
        type: string
        required: false
  workflow_call:
    inputs:
      variant:
        description: 'Prod for both Production and Staging.'
        type: string
        required: false
      version:
        description: 'version passed'
        type: string
        required: false

env:
  LOCAL_RELEASE_KEYSTORE_FILENAME: '_signed_keystore.keystore'
  _KEYSTORE_PASSWORD: ${{ secrets._KEYSTORE_PASSWORD }}
  _KEY_ALIAS: ${{ secrets._KEY_ALIAS }}
  _KEY_ALIAS_P: ${{ secrets._KEY_ALIAS_P }}
  VARIANT: ${{ github.event.inputs.variant }}
  VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Print Inputs
      id: print_inputs
      env:
        VARIANT: ${{ github.event.inputs.variant }}
        VERSION: ${{ github.event.inputs.version }}
      run: |
            echo "****INPUT**** VARIANT:$VARIANT"
            echo "****INPUT**** VERSION:$VERSION"

    - name: Retrieve keystore
      env:
        KEYSTORE_FILE_BASE64: ${{ secrets._SIGNED_KEYSTORE }}
      run: |
          echo "$KEYSTORE_FILE_BASE64" | base64 --decode > _signed_keystore.keystore
          keystore_path=$(realpath _signed_keystore.keystore)
          echo "KEYSTORE_PATH=${keystore_path}" >> "$GITHUB_ENV"
          md5sum ${keystore_path}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Staging Debug
      id: build_staging_debug
      continue-on-error: false
      run: ./gradlew bundleStagingDebug

    - name: Build Production Release
      id: build_production_release
      if: ${{ inputs.variant == 'Prod' }}
      continue-on-error: false
      env:
       _KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
      run: ./gradlew bundleProductionRelease

    - name: Summary
      id: summary
      continue-on-error: false
      env:
        _ACTOR: ${{ github.actor }}
        _RUN_NUMBER: ${{ github.run_number }}
        _BRANCH: ${{ github.ref_name }}
        _BUILD_VARIANT_INPUT: ${{ inputs.variant }}
        _BUILD_VERSION_INPUT: ${{ inputs.version }}
        _STAGING_DEBUG_SUCCESS: ${{ steps.build_staging_debug.conclusion == 'success' }}
        _PRODUCTION_RELEASE_SUCCESS: ${{ steps.build_production_release.conclusion == 'success' }}
      run: |
          echo "********************************OUTPUT*************************************"
          echo "$_ACTOR Triggered a Build"
          echo "Run Number: $_RUN_NUMBER"
          echo "Branch: $_BRANCH"
          echo "Build Variant Input: $_BUILD_VARIANT_INPUT"
          echo "Build Version Input: $_BUILD_VERSION_INPUT"
          echo "Staging debug was successful: $_STAGING_DEBUG_SUCCESS"
          echo "Production Release was successful: $_PRODUCTION_RELEASE_SUCCESS"
          echo "**********************************END***************************************"
