name: Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: string
        required: false

env:
  LOCAL_RELEASE_KEYSTORE_FILENAME: '_signed_keystore.keystore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Retrieve keystore
      env:
        KEYSTORE_FILE_BASE64: ${{ secrets._SIGNED_KEYSTORE }}
      run: |
          echo "$KEYSTORE_FILE_BASE64" | base64 --decode > _signed_keystore.keystore
          keystore_path=$(realpath _signed_keystore.keystore)
          echo "KEYSTORE_PATH=${keystore_path}" >> "$GITHUB_ENV"
          md5sum ${keystore_path}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      id: build_production_release
      continue-on-error: false
      env:
       _KEYSTORE: ${{ env.KEYSTORE_PATH }}
       _KEYSTORE_PASSWORD: ${{ secrets._KEYSTORE_PASSWORD }}
       _KEY_ALIAS: ${{ env._KEY_ALIAS }}
       _KEY_PASSWORD: ${{ secrets._KEY_AlIAS_PASSWORD }}
      run: ./gradlew bundleProductionRelease
