name: Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: string
        required: false

env:
  LOCAL_RELEASE_KEYSTORE_FILENAME: '_signed_keystore.keystore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Retrieve keystore
      env:
        KEYSTORE_FILE_BASE64: ${{ secrets._SIGNED_KEYSTORE }}
      run: |
          echo "MIIJ8AIBAzCCCZoGCSqGSIb3DQEHAaCCCYsEggmHMIIJgzCCBboGCSqGSIb3DQEHAaCCBasEggWnMIIFozCCBZ8GCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFM6ZTK2eTM3U4B9z5SjvCSVFPWSLAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQBZmM2Enz2U5szaKlgHdXJwSCBNBJ4eW+e+0YntYSZ7YPoT3AJa+mRHWY3THOO4M2Dlmtv6j0WqXVBEXOVbxEktYMtJ7XqzE79K89HiZSOzgdgg/iEIHTgpMhjhqh0yCkuuSiFqpBpIFQSzlRT0JlNnj8NLkQsZOd+hh/q+4A+99kXxz5rV5zq9X/R2/R39dhqGTay/0jY6GBlY1LR5MaFt09gpt/DwU8IpbiA9l9DOiFABdhoEpkeJlnztdJaOeUXK3ly+rIt1ck+XMglSlUEWkhrg7Zl8Sk8SjD+5d8QedvF7E0gZf03h+LFz3aK0V7KmFHswQZm40Ik48PVhouko9WZz3vZj+zTBf0LRicNp4NA+xspGuloFGtxeRLhvVAJS4F2Dei4QSiqijW6Ff2zt4uxXRj7HcueY6j7uDzLYifCErhwsWQb5QOl2TPVAvD6HTBT0VpWwO3J2efiI47b+47DWdO6lvyhFvqw1Zvnd7I7tMrhdtsbDSmeI7W7d8JTbv/4KD2FpG9B2HjAX1VFyfYHdvFIsIKM3iVxEyLsjfv4cgIWjaSzz1AfrVagVgODQfhRr8yI+22941TgtTGWA28iHgafEkos0hnuT4mqhGbMYdvJB/9Qke+WvXDPyCKoMfAs2mQTj+SW7CddiruaWDAyla8PHpHONhBIQ+TMYSFQSnlDycvxEETdXUOTw5Sc1Uul986dzWtAEEiULWGp6D0h9ElbIYYCAra1kjERr4frv1gb0yT9jS4SsPaL7QTE4d3GWDsS5Qw2D10eUl4jSkBGbCk78hAjGo2WxLng/YAHq7HsGogFd50E/Ds/8G5q4+03FPzGGRbHVZ6BovkvQELw/SoiDbdUflMfsZ3sgvzK0yemZnLr37rbhPp+FGO30gYuy85ip2skE/bPh+yzGajeYeW51yygn+vOKEv7UDMzP5mit3XBzCDbG6rttUy6vALyMrr0M6GER8O6BeeZl3YyzGitm0MSTXBVi7ng+Jo1qYAsVdnCHg/lr7Q6Oj4C4IfBaE8s5s6suCabBezWaMkxmguhmIX64ZgJ35yJsdFq+rm09sJ4oGJqJU0DYC8bYM1ZLrsC+gbPkka6zetSXG+tO5+wEO52Vem8sdtXerS6e8z9xqp1o/iAW8ZEJWMjwz7ctUbZt1vJuIa+Gab/l7zVWtiSf8TnaeHK0k0r8xjia7mSC7Vxycht4bR/IGHr9BkIV237Y9P/Z+vI95pod+zYNjw61x8uIkn7tG/kzPZPFrogvVDgDKeSbO4lPUM8fHTvYmeWRMkexL4zqnWpyfz3XIcdAaFCR5BTwkS2hsJXg29QfD+IKrm7zFrXd9NN0qU+NESO8vonvID8ySjyc7VxlrVWTNU5ZBtqj8lr2OCtyyFJjiPlcqarPNTIqOlfO1NQ3h1Zmqx34DVjHtvROJgo70f4WdRK+Hg21ccHBJ0XwJ/5L4OoUJtOCtbkAx90C/KUG6kTFv7WZW0hfiZEYMSoKmFAV51COKKFb9WPpCal85rl6ZzDStrE5dB3mD+5L1prVCzGxoMKl43kVXYr0JP18HMCWDG60S6y7wEvPluMYekSmCMNOhSDdv+eAkHWyYrVuA+fNlZsDPYTGc5rmL73wZyUN3ZpmcNSEUfTI4zFuCwE060nMPELYmigqEsmivSEzFMMCcGCSqGSIb3DQEJFDEaHhgAXwBwAHIAbwBkAF8AcwBpAGcAbgBlAGQwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTczNTM1MjgyOTEzOTCCA8EGCSqGSIb3DQEHBqCCA7IwggOuAgEAMIIDpwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBQGFsyTp26pg/KGdoSIvxQJlbPgJgICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEOWvo3kGVNaEXf/F5sWYf8GAggMwpchj1KgN5Ag1CnQgYwyvqLmeNsdU7CYqqj3Hij+SaufxebKcH7+d+LrRCxYjC4aV34pZeCHRC1icLXXqA4NadJQx2JeGs18ZRpNVgevEteagxZz1anAZFQ0NDYsPIUmkMTimieyeVob8hJLBlt+Z4k2uPkwP+tP5joepVV0sIFDMyes8UfPDcL9VVQVLrxaU06AYIZEzrq25QyxDGNYhOwmcLiyQTVbaqciB0HTDRzEwtUbRosXB+4nxPE8sEpSyL//XT/OpTcbTUHtzWHiBNWxcK/oG2kPZ2lASSlRPNoeL4Pcn/4XxAr5Oryb3xL9bFSexwunfjUBEZ3zp1+o3FWBg+4X9po5zCVLo9KUlvz803htthXOkocJbxzhR0pPADywbHoXCe6Fj8MzuaeBq7j+ZRmprtCY1C/JXLAyuCPQEkh10OdfLYEBBRP0LUpDn8UuUy/MvrVeBF8aY1QFE/3C37/f/Gdp2OqEm8kVtprUN3hTUzaviPtW+xyjv0gIDWPyNXDdAD2qxR7dbUv/RHj35g+Xd0e6To/kwmn3PLl2yL51jO/3NN0AUemaEVlGOWJ04vACYU6ZMKDyYAkOTNAhSsSiyEGfFeeMBS5qkAeAAfhkqId7VayYzuqMKx45eqBqqAhOL1733s4iKkpiVM+XdzgF8BfE/eoAHKeHnuwQXs1Mg5MzKXgAWxMcAT6YqV6jmit9ZAra1sJ1euGrpUFKrdNIaPKbHXmcs5jh4WDbISZqc9JIxZJ0ZKJuYXgzlygeuKUexpIFiYwAXW405aD4IFjlPddgmMS+b86QEam+U4y4q8o7a4cPJnQtxOBRslQbdcaoMRnbjLSeVXbqblh9ftBKc9GDp0yFet7BJW11U1PqeE69e4gvMLbUg11r43VT1ktyGOtgPhpjlOXqqEPN0kJV2UaC4Ov8Vj+abJZQbPWGqpt+Q7BQ/ua2Ba+6ic+4xkoHsx4Whd4JExcQ1LaJ+mIDg1N7VGZL0nUYG/JhgJ/+w8wBhd3NzNRfpkDATodD5gtxzXB/drvPeUgGYGDD5fhGcwN5zuVgF6E5eykyMxnalwQgT3cCtLXZs2Vn8ME0wMTANBglghkgBZQMEAgEFAAQguRNAvSf8UTr8ecUDuvsYQQloZCjcnG7kjxkL49ijswMEFJwdWeqxEBjdVIQgDz2oL/UPHzBFAgInEA==" | base64 --decode > _signed_keystore.keystore
          keystore_path=$(realpath _signed_keystore.keystore)
          echo "KEYSTORE_PATH=${keystore_path}" >> "$GITHUB_ENV"
          md5sum ${keystore_path}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      id: build_production_release
      continue-on-error: false
      env:
       _KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
       _KEYSTORE_PASSWORD: ${{ secrets._KEYSTORE_PASSWORD }}
       _KEY_ALIAS: ${{ secrets._KEY_ALIAS }}
       _KEY_ALIAS_PASSWORD: ${{ secrets._KEY_AlIAS_PASSWORD }}
      run: ./gradlew bundleProductionRelease
