name: Build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: string
        required: true
  repository_dispatch:
    types: [trigger-build-process]
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: string
        required: true

env:
  LOCAL_RELEASE_KEYSTORE_FILENAME: 'release_keystore.keystore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Retrieve keystore
      env:
        KEYSTORE_FILE_BASE64: ${{ secrets._RELEASE_KEYSTORE }}
      run: |
          echo "$KEYSTORE_FILE_BASE64" | base64 --decode > release_keystore.keystore
          keystore_path=$(realpath release_keystore.keystore)
          echo "KEYSTORE_PATH=${keystore_path}" >> "$GITHUB_ENV"
          md5sum ${keystore_path}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      id: build_production_release
      continue-on-error: false
      env:
       _KEYSTORE: ${{ env.KEYSTORE_PATH }}
       _KEYSTORE_PASSWORD: ${{ secrets._KEYSTORE_PASSWORD }}
       _KEY_ALIAS: ${{ secrets._KEY_ALIAS }}
       _KEY_PASSWORD: ${{ secrets._KEY_AlIAS_PASSWORD }}
      run: ./gradlew --no-daemon bundleProductionSigned
